const khmerMapping:any = {
    'ឆ': ['Q'],
    'ឈ': ['RIGHT_SHIFT', 'Q'],
    'ឹ': ['W'],
    'ឺ': ['RIGHT_SHIFT', 'W'],
    'េ': ['E'],
    'ែ': ['RIGHT_SHIFT', 'E'],
    'រ': ['R'],
    'ត': ['T'],
    'ទ': ['RIGHT_SHIFT', 'T'],
    'ៜ': ['ALT_GR', 'Q'],
    '៝': ['ALT_GR', 'W'],
    'ឯ': ['ALT_GR', 'E'],
    'ឫ': ['ALT_GR', 'R'],
    'ឬ': ['RIGHT_SHIFT', 'R'],
    'ឨ': ['ALT_GR', 'T'],
    'ា': ['A'],
    'ាំ': ['RIGHT_SHIFT', 'A'],
    'ស': ['S'],
    'ៃ': ['RIGHT_SHIFT', 'S'],
    'ដ': ['D'],
    'ឌ': ['RIGHT_SHIFT', 'D'],
    'ថ': ['F'],
    'ធ': ['RIGHT_SHIFT', 'F'],
    'ង': ['G'],
    'អ': ['RIGHT_SHIFT', 'G'],
    'ឋ': ['Z'],
    'ឍ': ['RIGHT_SHIFT', 'Z'],
    'ខ': ['X'],
    'ឃ': ['RIGHT_SHIFT', 'X'],
    'ច': ['C'],
    'ជ': ['RIGHT_SHIFT', 'C'],
    'វ': ['V'],
    'េះ': ['RIGHT_SHIFT', 'V'],
    'ប': ['B'],
    'ព': ['RIGHT_SHIFT', 'B'],
    'ឞ': ['ALT_GR', 'B'],
    'យ': ['Y'],
    'ួ': ['LEFT_SHIFT', 'Y'],
    'ុ': ['U'],
    'ូ': ['LEFT_SHIFT', 'U'],
    'ិ': ['I'],
    'ី': ['LEFT_SHIFT', 'I'],
    'ោ': ['O'],
    'ៅ': ['LEFT_SHIFT', 'O'],
    'ផ': ['P'],
    'ភ': ['LEFT_SHIFT', 'P'],
    'ឦ': ['ALT_GR', 'I'],
    'ឱ': ['ALT_GR', 'O'],
    'ឰ': ['ALT_GR', 'P'],
    'ហ': ['H'],
    'ះ': ['LEFT_SHIFT', 'H'],
    '្': ['J'],
    'ញ': ['LEFT_SHIFT', 'J'],
    'ក': ['K'],
    'គ': ['LEFT_SHIFT', 'K'],
    'ល': ['L'],
    'ឡ': ['LEFT_SHIFT', 'L'],
    'ឝ': ['ALT_GR', 'K'],
    'ន': ['N'],
    'ណ': ['LEFT_SHIFT', 'N'],
    'ម': ['M'],
    'ំ': ['LEFT_SHIFT', 'M'],
    '«': ['ZWJ'],
    '»': ['RIGHT_SHIFT', 'ZWJ'],
    '១': ['one'],
    '!': ['RIGHT_SHIFT', 'one'],
    '២': ['two'],
    'ៗ': ['RIGHT_SHIFT', 'two'],
    '៣': ['three'],
    '"': ['RIGHT_SHIFT', 'three'],
    '៤': ['four'],
    '៛': ['RIGHT_SHIFT', 'four'],
    '៥': ['five'],
    '%': ['RIGHT_SHIFT', 'five'],
    '៦': ['six'],
    '៍': ['LEFT_SHIFT', 'six'],
    '៧': ['seven'],
    '័': ['LEFT_SHIFT', 'seven'],
    '៨': ['eight'],
    '៏': ['LEFT_SHIFT', 'eight'],
    '៩': ['nine'],
    '(': ['LEFT_SHIFT', 'nine'],
    '០': ['zero'],
    ')': ['LEFT_SHIFT', 'zero'],
    'ឥ': ['DASH'],
    '៌': ['LEFT_SHIFT', 'DASH'],
    'ឲ': ['EQUAL'],
    '=': ['LEFT_SHIFT', 'EQUAL'],
    '@': ['ALT_GR', 'two'],
    '៑': ['ALT_GR', 'three'],
    '$': ['ALT_GR', 'four'],
    '€': ['ALT_GR', 'five'],
    '៙': ['ALT_GR', 'six'],
    '៚': ['ALT_GR', 'seven'],
    '*': ['ALT_GR', 'eight'],
    '{': ['ALT_GR', 'nine'],
    '}': ['ALT_GR', 'zero'],
    'x': ['ALT_GR', 'DASH'],
    '៎': ['ALT_GR', 'EQUAL'],
    'ឮ': ['BACKSLASH'],
    'ឭ': ['LEFT_SHIFT', 'BACKSLASH'],
    'ៀ': ['LEFT_BRACKET'],
    'ឿ': ['LEFT_SHIFT', 'LEFT_BRACKET'],
    'ឪ': ['RIGHT_BRACKET'],
    'ឧ': ['LEFT_SHIFT', 'RIGHT_BRACKET'],
    'ើ': ['SEMICOLON'],
    'ោះ': ['LEFT_SHIFT', 'SEMICOLON'],
    '់': ['QUOTE'],
    '៉': ['LEFT_SHIFT', 'QUOTE'],
    'ុំ': ['COMMA'],
    'ុះ': ['LEFT_SHIFT', 'COMMA'],
    '។': ['POINT'],
    '៕': ['LEFT_SHIFT', 'POINT'],
    '៊': ['SLASH'],
    'ុី': ['SLASH'],
    '?': ['LEFT_SHIFT', 'SLASH'],
    '\\': ['ALT_GR', 'BACKSLASH'],
    'ឩ': ['ALT_GR', 'LEFT_BRACKET'],
    'ឳ': ['ALT_GR', 'RIGHT_BRACKET'],
    '៖': ['ALT_GR', 'SEMICOLON'],
    'ៈ': ['ALT_GR', 'QUOTE'],
    ',': ['ALT_GR', 'COMMA'],
    '.': ['ALT_GR', 'POINT'],
    '/': ['ALT_GR', 'SLASH'],
    '​': ['SPACE'],
    ' ': ['LEFT_SHIFT', 'SPACE'],
    // ',': ['ALT_GR', 'COMMA'],
    // '.': ['ALT_GR', 'POINT'],
    // '/': ['ALT_GR', 'SLASH'],
    // '​': ['SPACE'],
    'a':['A'],
    'A':['LEFT_SHIFT','A'],
    'b':['B'],
    'B':['LEFT_SHIFT','B'],
    'c':['C'],
    'C':['LEFT_SHIFT','C'],
    'd':['D'],
    'D':['LEFT_SHIFT','D'],
    'e':['E'],
    'E':['LEFT_SHIFT','E'],
    'f':['F'],
    'F':['LEFT_SHIFT','F'],
    'g':['G'],
    'G':['LEFT_SHIFT','G'],
    'h':['H'],
    'H':['LEFT_SHIFT','H'],
    'i':['I'],
    'I':['LEFT_SHIFT','I'],
    'j':['J'],
    'J':['LEFT_SHIFT','J'],
    'k':['K'],
    'K':['LEFT_SHIFT','K'],
    'l':['L'],
    'L':['LEFT_SHIFT','L'],
    'm':['M'],
    'M':['LEFT_SHIFT','M'],
    'n':['N'],
    'N':['LEFT_SHIFT','N'],
    'o':['O'],
    'O':['LEFT_SHIFT','O'],
    'p':['P'],
    'P':['LEFT_SHIFT','P'],
    'q':['Q'],
    'Q':['LEFT_SHIFT','Q'],
    'r':['R'],
    'R':['LEFT_SHIFT','R'],
    's':['S'],
    'S':['LEFT_SHIFT','S'],
    't':['T'],
    'T':['LEFT_SHIFT','T'],
    'u':['U'],
    'U':['LEFT_SHIFT','U'],
    'v':['V'],
    'V':['LEFT_SHIFT','V'],
    'w':['W'],
    'W':['LEFT_SHIFT','W'],
    // 'x':['X'],
    'X':['LEFT_SHIFT','X'],
    'y':['Y'],
    'Y':['LEFT_SHIFT','Y'],
    'z':['Z'],
    'Z':['LEFT_SHIFT','Z'],
    '-':['HYPHEN'],

    '1':['one'],
    '2':['two'],
    '3':['three'],
    '4':['four'],
    '5':['five'],
    '6':['six'],
    '7':['seven'],
    '8':['eight'],
    '9':['nine'],
    '0':['zero'],


}
export default khmerMapping;